services:
  - type: web
    name: studybuddy-backend
    runtime: node
    repo: https://github.com/mrggitau/StudyBuddy
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production